name: Push Workflow - Format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1
      with:
        args: format
        src: ./
        config: .pyproject.toml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'style fixes by ruff'

