name: Push Workflow - Format

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1
      with:
        args: format
        src: ./
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Add automated style fixes by ruff'
