#This workflow installs Python dependencies, tests, and lints.

name: Python application

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        pipx install poetry
        poetry install
    - name: Lint with ruff
      run: |
        poetry run ruff check --output-format=github .
    - name: Test with pytest
      run: |
        poetry run pytest --cov --cov-report=html

